asr_vocab_filename: dict.wrd.txt
bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: /mnt/zhangyh/fairseq-AT/egs/pretrain-all/data_all_enfr_lcrm/sentencepiece.bpe.model
input_channels: 1
input_feat_per_channel: 80
sampling_alpha: 1.0
share_src_and_tgt: false
specaugment:
  freq_mask_F: 27
  freq_mask_N: 1
  time_mask_N: 1
  time_mask_T: 100
  time_mask_p: 1.0
  time_wrap_W: 0
src_bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: /mnt/zhangyh/fairseq-AT/egs/pretrain-all/data_all_enfr_lcrm/sentencepiece.bpe.model
use_audio_input: true
vocab_filename: dict.wrd.txt
cluster_dict: kmeans100.convert.txt
#add_blank_noise: True
